words = [
    "airbnb",
    "djot",
    "esgleam",
    "giscus",
    "glimra",
    "gql",
    "graphql",
    "imcquee",
    "juneteenth",
    "linkify",
    "lustre",
    "negotiables",
    "nextjs",
    "noopener",
    "noreferrer",
    "nuqs",
    "prisma",
    "rica",
    "simplifile",
    "ssg",
    "tanstack",
    "walkability",
    "è·³",
]
